{
 "title": "Finance API - Overview",
 "refresh": "10s",
 "panels": [
  {
   "title": "Requests / min (total)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "60 * sum(rate(http_server_requests_seconds_count{job=\"finance-api\", uri!~\"/actuator.*\"}[1m]))"
    }
   ]
  },
  {
   "title": "Success 2xx / min",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "60 * (sum(rate(http_server_requests_seconds_count{job=\"finance-api\", status=~\"2..\", uri!~\"/actuator.*\"}[1m])) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Errors 4xx / min",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "60 * (sum(rate(http_server_requests_seconds_count{job=\"finance-api\", status=~\"4..\", uri!~\"/actuator.*\"}[1m])) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Errors 5xx / min",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "60 * (sum(rate(http_server_requests_seconds_count{job=\"finance-api\", status=~\"5..\", uri!~\"/actuator.*\"}[1m])) OR on() vector(0))"
    }
   ]
  },
  {
   "title": "Latency p95 (ms)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "1000 * histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job=\"finance-api\", uri!~\"/actuator.*\"}[10m])) by (le))"
    }
   ]
  },
  {
   "title": "CPU % (process)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 16, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "100 * avg(process_cpu_usage{job=\"finance-api\"})"
    }
   ]
  },
  {
   "title": "Finance API UP",
   "type": "stat",
   "gridPos": { "x": 0, "y": 24, "w": 6, "h": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(up{job=\"finance-api\"}[2m])"
    }
   ]
  },
  {
   "title": "Top endpoints (RPS)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 24, "w": 18, "h": 10 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(http_server_requests_seconds_count{job=\"finance-api\", uri!~\"/actuator.*\", uri!~\"/admin/monitoring.*\"}[1m])) by (uri, method))",
     "legendFormat": "{{method}} {{uri}}"
    }
   ]
  }
 ]
}